Fix deprecated GitHub action commands
dbt-labs/homebrew-dbt pull request #185
Opened 2022-10-27 20:51 UTC by kevinneville

resolves #

### Description

### Checklist

- [ ] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [ ] I have run this code in development and it appears to resolve the stated issue
- [ ] This PR includes tests, or tests are not required/relevant for this PR

2022-10-27 20:57 UTC, kevinneville commented on .github/workflows/formula.yml
> -            echo ::set-output name=filename-with-version::"Formula/${{ github.event.inputs.dbt-package }}@${{ steps.semver.outputs.base-version }}-${{ steps.semver.outputs.pre-release }}.rb"
Please have an extra look at row 99, 102 & 104, I am not 100% sure about those.

2022-12-23 19:52 UTC, emmyoop requested changes
Thanks for updating this for the deprecation and also doing a little cleanup in formatting on the other workflow!  I had a small reorganization request that I'll go ahead and merge in to get this added to main.

2022-12-23 19:52 UTC, emmyoop commented on .github/workflows/formula.yml
> +            echo filename-with-version="Formula/${{ github.event.inputs.dbt-package }}@${{ steps.semver.outputs.base-version }}-${{ steps.semver.outputs.pre-release }}.rb" >> $GITHUB_OUTPUT
FILENAME_WITH_VERSION="Formula/${{ github.event.inputs.dbt-package }}@${{ steps.semver.outputs.base-version }}-${{ steps.semver.outputs.pre-release }}.rb"

2022-12-23 19:52 UTC, emmyoop commented on .github/workflows/formula.yml
> +            echo filename-with-version="Formula/${{ github.event.inputs.dbt-package }}@${{ steps.semver.outputs.version }}.rb" >> $GITHUB_OUTPUT
```suggestion
            FILENAME_WITH_VERSION="Formula/${{ github.event.inputs.dbt-package }}@${{ steps.semver.outputs.version }}.rb"
```

2022-12-23 19:52 UTC, emmyoop commented on .github/workflows/formula.yml
> +          echo filename="Formula/${{ github.event.inputs.dbt-package }}.rb" >> $GITHUB_OUTPUT
```suggestion
          echo "filename-with-version=${FILENAME_WITH_VERSION}" >> $GITHUB_OUTPUT
          FILENAME="Formula/${{ github.event.inputs.dbt-package }}.rb"
          echo "filename=${FILENAME}" >> $GITHUB_OUTPUT
```

2022-12-23 19:52 UTC, emmyoop commented on .github/workflows/formula.yml
> +          echo filename="Formula/${{ github.event.inputs.dbt-package }}.rb" >> $GITHUB_OUTPUT
The above three changes all go together and make the assignment a little more clear.  What you had wasn't wrong but this makes the workflow a little easier to read.

2022-12-23 19:52 UTC, emmyoop commented on .github/workflows/installation-tests.yml
> +# It then run 'dbt --version' to verify the installation was successful.
```suggestion
# It then runs 'dbt --version' to verify the installation was successful.
```

2022-12-23 19:53 UTC, emmyoop commented on .github/workflows/formula.yml
> +            echo filename-with-version="Formula/${{ github.event.inputs.dbt-package }}@${{ steps.semver.outputs.base-version }}-${{ steps.semver.outputs.pre-release }}.rb" >> $GITHUB_OUTPUT
```suggestion
            FILENAME_WITH_VERSION="Formula/${{ github.event.inputs.dbt-package }}@${{ steps.semver.outputs.base-version }}-${{ steps.semver.outputs.pre-release }}.rb"
```

2022-12-23 19:58 UTC, emmyoop approved these changes
@kevinneville thanks so much for helping clean up these workflows!

2022-12-23 19:59 UTC, merged